VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-precise64-chef"
  config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box"

  config.vm.network :private_network, ip: "10.0.0.10"
  config.vm.hostname = "detroit"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../"

    chef.json = {
      "database" => {
        "user" => "root",
        "password" => "",
        "host" => "10.0.1.166"
      }
    }

    chef.add_recipe "detroit::default"
    chef.add_recipe "detroit::deploy"
  end
end
